linters-settings:

golint:
  min-confidence: 0

misspell:
  locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - golint
    - ineffassign
    - gosimple
    - deadcode
    - structcheck
    - unused
    - errcheck

service:
  golangci-lint-version: 1.32.2 # use the fixed version to not introduce new linters unexpectedly
